# version: '3.8'

# services:
#   mongodb:
#     image: mongo
#     restart: always
#     ports:
#       - '27017:27017'
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: admin
#     volumes:
#       - mongodb_data:/data/db

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - '8081:8081'
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#       ME_CONFIG_MONGODB_ADMINPASSWORD: admin
#       ME_CONFIG_MONGODB_SERVER: mongo
#       ME_CONFIG_BASICAUTH_USERNAME: admin
#       ME_CONFIG_BASICAUTH_PASSWORD: admin

# volumes:
#   mongodb_data:


# Access GUI at: http://localhost:8081
# Login: admin
# Password: admin

# Mongo URI for Compass:

# mongodb://admin:admin@localhost:27017/?authSource=admin





services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
  
volumes:
  mongodb_data: 



# services:
#   mongodb:
#     image: mongo
#     restart: always
#     ports:
#       - '27017:27017'
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: admin
#     volumes:
#       - mongodb_data:/data/db
  
# volumes:
#   mongodb_data:
